#ifndef __CREDENTIALS_H_INCLUDED
#define __CREDENTIALS_H_INCLUDED

#define WIFI_SSID "THE SSID"
#define WIFI_PASSWORD "THE PASSWORD"
#define MQTT_SERVER "IP OF MQTT SERVER" 

#endif //__CREDENTIALS_H_INCLUDED

// vim:ai:cin:sts=2 sw=2 ft=cpp
